actors:
  anozon:
    image_url: /images/actors/anozon.png
    name: anozon
    url: https://anozon.me
  aki:
    image_url: /images/actors/bob.png
    name: aki
    url: http://sns.example.com/bob
author: anozon
description: Akispace.fm
description_long: "フロントエンジニアとサーバーエンジニアによる雑談ラジオ"
email: guild0105@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: akispacefm
itunes_podcast_url:
keywords: frontend,javascript,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Akispace.fm
url: https://elzup.github.io/akispacefm/
# url: https://akispace.anozon.me
